name: Nodejs ci

on:
  push:
    branches: ["main"]
    paths: ["backend/**"]
  pull_request:
    branches : ["main"] 
    paths: ["backend/**"]

jobs:
  build:
      runs-on: self-hosted
  
      steps:
        - uses: actions/checkout@v3
        - run: npm install
          working-directory: ./backend

        - name: create .env file
          working-directory: ./backend
          run: |
            touch .env
            echo "${{ secrets.CHATBOX_ENV }}" > .env

        - name: Deploy
          run: |
            pm2 stop chatbox || true
            pm2 delete chatbox || true
            pm2 --interpreter=$(which ts-node) start ./backend/main.ts --name chatbox
          working-directory: ./backend
