name: Nodejs ci

on:
  push:
    branches: ["main"]
  pull_request:
    branches : ["main"] 

jobs:
  build:
      runs-on: self-hosted
  
      steps:
        - uses: actions/checkout@v3

        - name: change directory
          run: cd backend

        - name: create .env file
          run: |
            touch .env
            echo "${{ secrets.CHATBOX_ENV }}" > .env

        - name: install dependencies
          run: npm install

        - name: remove old process
          run: pm2 delete chatbox-server || true

        - name: start new server
          run: pm2 start --interpreter=/home/admin/.nvm/versions/node/v20.9.0/bin/ts-node main.ts --name chatbox-server
